### ISSUE TITLE
Setup Test Instance

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#10]
Setup a CATMAID test instance with a small volume to test the Catsop components.

Might a virtual machine be a good idea? It would allow for snapshots, so we could easily go back to a fresh install.

**Comment by tomka** [comment]
A test instance is certainly a good idea. @unidesigner and me will set one up today. We also thought it might be helpful to not start with a full CATMAID instance, but with a small Django application that makes use of the django-sopnet application (just like CATMAID would). This could allow much easier debugging and testing.
