### ISSUE TITLE
SliceGuarantor does not extract slices

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#11]
When requesting block (0,0,0) and (0,0,20) (which does not exist) on a test stack of 20 sections @ 1Kx1K, with blocksize (16,16,8) nothing happens. See test_pysopnet.py, first test case, commit 847d55c5655ea1acf76b7db84bd94c16d037aa48 in python-sopnet.

Log message is "All blocks have already been extracted".

**Comment by funkey** [comment]
The problem was that the BlockManager was not informed about the size of the volume, and thus concluded something wrong. Please use exceptions for these cases.

**Comment by larrylindsey** [comment]
I think this essentially a duplicate of issue #11

**Comment by funkey** [comment]
Duplicate of itself? ;)

Anyway, I will implement out-of-bound checks in the python wrappers and throw exceptions there.
