### ISSUE TITLE
getLocation() in Block

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#13]
To translate the missing Blocks (returned by the *Guarantors) back to the block locations, it would be nice if Block would store the location and has a getLocation(). Alternatively, BlockManager could provide this functionality.

**Comment by larrylindsey** [comment]
Both Block and Blocks inherit from Box<unsigned int>. Are the location() and size() functions enough?

**Comment by funkey** [comment]
Sorry, my description was not very clear. What I need is the index of a block. location() and size() are in pixels, if I am not mistaken.

**Comment by larrylindsey** [comment]
OK. By index, do you mean the unique ID? Block has getID(). I could add a function to Blocks:

std::vector<unsigned int> Blocks::blockIDs();

**Comment by funkey** [comment]
No, I mean the index in the 3D volume.

**Comment by larrylindsey** [comment]
Do you mean what I've been calling the block coordinates?

**Comment by funkey** [comment]
Yes!

**Comment by larrylindsey** [comment]
Added in 3e1f4e1c0875780e3fe453d484173f261a67ba76
