### ISSUE TITLE
current "blockwise" does not compile

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#15]
Undefined reference to EndExtractor::EndExtractor() in commit https://github.com/catsop/python-sopnet/commit/bb13cdfdc6ab102ddd74edc587b72c108eeca33e

Forgot to check-in file?

By the way, how does "blockwise" relate to "master"? Is there any reason not to merge with "master" once "blockwise" compiles?

**Comment by larrylindsey** [comment]
Its possible I forgot to push. My log shows it checked in as of 4/18. Give it another try?

**Comment by larrylindsey** [comment]
May I close this?

**Comment by funkey** [comment]
Compiles now.
