### ISSUE TITLE
*Guarantors should not be SimpleProcessNodes

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#18]
SimpleProcessNodes produce overhead. The *Guarantors don't need to be process nodes, since they are not used in a pipeline. They just use pipeline components in their implementation.

**Comment by funkey** [comment]
Converted SegmentGuarantor. See this class for reference.

**Comment by aschampion** [comment]
Closed with catsop/python-sopnet@fdcfc53093fc41aeb9c5234507410fed91d5ee51
