### ISSUE TITLE
Finish SolutionGuarantor

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#3]
Implement and test the SolutionGuarantor.

**Comment by larrylindsey** [comment]
SolutionGuarantor is finished and tested for expected usage cases.

**Comment by larrylindsey** [comment]
SolutionGuarantor is finished and tested for expected usage cases.

**Comment by larrylindsey** [comment]
SolutionGuarantor is finished and tested for expected usage cases.

**Comment by larrylindsey** [comment]
SolutionGuarantor is finished and tested for expected usage cases.

**Comment by larrylindsey** [comment]
That was weird.
