### ISSUE TITLE
Blocks should belong to the project, not the stack

### ISSUE THREAD

**Issue by larrylindsey** [catsop/catsop#33]

**Comment by unidesigner** [comment]
No, I think they should belong to the stack. Projects can have many stacks in the current catmaid world, each one translated relative to the project origo.

**Comment by funkey** [comment]
Projects can have many stacks, but in my opinion it doesn't make sense to have different segments for each stack. What would be the use case? One project contains one volume. Each volume has slices and segments. The stacks are only different views (raw, membrane prediction) of the same volume.

**Comment by unidesigner** [comment]
The model in CATMAID is like this: A project can have multiple stacks. Each stack has a translation field (x,y,z) which defines an offset relative to the project coordinate system. Each stack can have different voxel resolutions and dimensions. The idea is that you can associate multi-modal images in the same project (like low resolution light microscopy stacks) together with raw EM stacks. A stack can have multiple overlays. And overlay has exactly the same dimension as its parent stack, but its own image source and title.
For the case of derived stacks, computed from the raw data, like probability maps, we should use overlays that are associated to the raw stack, as they should have exactly the same dimensions.

A Block is a concept associated to the processing of a stack (raw, probability maps etc - all in the same coordinate system), thus I'd keep it associated to a stack, in particular the raw image stack.

We store skeleton coordinates in project space, that is in physical space in nm (i.e taking the stack voxel coordinates, multiply by resolution and add translation). I agree that it could make sense to store geometric information about the slices/segments in physical coordinates directly in the database (vs. computing it onthefly on the client) - but then, catsop processing task always need to care about the physical coordinates (and reverse this back to stack-based coordinates) which is tedious, for instance for bounding box queries etc. It's easy to get the stack-based coordinates from the CATMAID UI and let the backend operate only in stack-based coordinates.

**Comment by larrylindsey** [comment]
My thinking is a little more mundane: I want to support the case in which we may have multiple projects pointing to the same stack. The block says is not dependent on anything inherent to the stack. I would propose instead that Blocks belong to a (stack AND project), perhaps with a method for translating block geometry among stacks.

**Comment by unidesigner** [comment]
We should not make it more complicated than it already is. We had the use case of multiple projects pointing to the same stack only once, when we did independent reconstructions in the same stack. Given that we'd rather want people to collaboratively reconstruct semi-automatically in the same one-and-only stack, associating the block with the stack should be fine.

However, didn't we say we fix e.g. the block size for a given stack once and for all in the beginning? Do we want to support multiple configurations of the blocks, e.g. being able to change the specified block-size after we already extracted slices/segments?

**Comment by larrylindsey** [comment]
I wouldn't want to support multiple block configurations for the same project, no. It's possible that we could add the ability to change block sizes later, but for now I'd rather just assume that it will be static.

**Comment by larrylindsey** [comment]
Jan's point makes sense to me, too, although I think it would be complicated to associate a block/segment/slice set over multiple resolutions. Maybe it would make sense to designate an geometrically authoritative stack for a project for the purposes of storing these objects?

**Comment by unidesigner** [comment]
Yes, an authorative stack - this is what I tried to say in my lengthy response. And this authorative/main stack should be the stack with the raw image data.

Good to assume a static block size for now. That is, a configuration parameter for the pipeline.
