### ISSUE TITLE
Conflicting slices in solution

### ISSUE THREAD

**Issue by aschampion** [catsop/catsop#39]
The solved core currently in neurocity's `catsop` database includes segments containing conflicting slices. The following query should always return no rows:

``` sql
SELECT * 
FROM djsopnet_segmentsolution ssol1 
  JOIN djsopnet_segmentslice ss1 
    ON (ss1.segment_id = ssol1.segment_id)
  JOIN djsopnet_sliceconflictset scs 
    ON (ss1.slice_id = scs.slice_a_id OR ss1.slice_id = scs.slice_b_id)
  JOIN djsopnet_segmentslice ss2 
    ON ((ss2.slice_id = scs.slice_a_id OR ss2.slice_id = scs.slice_b_id)
        AND ss2.slice_id <> ss1.slice_id)
  JOIN djsopnet_segmentsolution ssol2 
    ON (ssol2.segment_id = ss2.segment_id)
  WHERE ss1.segment_id <> ss2.segment_id AND ssol1.core_id = ssol2.core_id
```

but currently returns 1614 rows. Possible culprits:
- `PostgreSqlSliceStore` is not correctly retrieving conflict sets from the database (they seem to be inserted correctly, since this bug was actually caught from visualizing results in CATMAID)
- Overlap constraints are not being constructed or enforced properly in `SolutionGuarantor`
- `PostgreSqlSegmentStore` is writing the solution incorrectly, which is unlikely given the simplicity.

**Comment by funkey** [comment]
I just realized that end segments involving the same slice always had the same hash. I fixed it in python-sopnet -- can you run your tests again and see whether this had any effect on this issue?

**Comment by aschampion** [comment]
Only one segment per slice was being stored and retrieved because of the hash collision. That's fixed now, but the issue doesn't seem to be resolved -- the row count of the above sanity check is up from 1614 to 1952. At least now that I can generate solutions (thanks! -- and thanks to Mark, not just on neurocity!) it should be much easier to debug.

**Comment by aschampion** [comment]
Another diagnostic query with interesting results:

``` sql
SELECT s.id, count(*)
FROM djsopnet_slice s
  JOIN djsopnet_segmentslice ss1 ON (ss1.slice_id = s.id)
  JOIN djsopnet_segmentslice ss2 ON (ss2.slice_id = s.id AND ss1.segment_id <> ss2.segment_id)
  WHERE EXISTS (SELECT 1 FROM djsopnet_segmentsolution ssol WHERE ssol.segment_id = ss1.segment_id)
    AND EXISTS (SELECT 1 FROM djsopnet_segmentsolution ssol WHERE ssol.segment_id = ss2.segment_id)
  GROUP BY s.id
    HAVING count(*) > 2
```

This shows all slices involved in more than two segments in the solution. Again, this query should return no rows (since any slice should be involved in at most two segments in the solution), but returns 36 rows. Interestingly, all anomalous slices are involved in exactly ~~12 segments in the solution.~~

Edit: make that 4 segments in the solution, 12 was just SQL counting combinations. Still, that all are 4 rather than 3 hints that some constraints are still being applied, only each segment is being assigned to two variables.

**Comment by aschampion** [comment]
The above query was fixed with catsop/python-sopnet@1f5ba52c41ef9ba237784956c68124256cc31217, reducing the number of offending rows in the original query to 1124.

The underlying cause for the original bug is that segments are being generated that contain conflicting slices. Again, a diagnostic query that should return zero rows:

``` sql
SELECT *
FROM djsopnet_segmentslice ss1
  JOIN djsopnet_segmentslice ss2 
    ON (ss1.segment_id = ss2.segment_id AND ss1.id <> ss2.id)
  JOIN djsopnet_sliceconflictset scs
    ON (scs.slice_a_id = ss1.slice_id AND scs.slice_b_id = ss2.slice_id);
```

but currently returns 5520. `SegmentGuarantor` does not read conflict sets when generating segments, so `SegmentExtractor` generates branch segments containing conflicting slices. I'll fix this tomorrow either in `SegmentGuarantor::getSlices` or directly in  `PostgreSqlSliceStore::getSlicesByBlocks`.

**Comment by funkey** [comment]
This fix is very interesting, since the constraints that you added should 
already be implied by the overlap and continuation constraints:

The overlap constraint should make sure not more than one segment is selected on 
one side of a conflict set (which, in particular, means not more than one 
segment from one side of a slice).

The continuation constraint should make sure that an equal number of segments is 
chosen on each side.

Together, not more than two segments should be chosen per slice. That your fix 
still makes a difference shows that something is wrong with the original 
constraints.

**Comment by aschampion** [comment]
Right, except most slices (~70%) aren't in any conflict set. The constraint can be enforced more parsimoniously in `addOverlapConstraints` by only being applied to slices not in a conflict set and only to segments on one side of the slice (with a value of 1 instead of 2). Since any slice not in conflict should be in the solution, we can even make it an equality constraint. Alternatively we could create and store a conflict set for each of these slices with only one member. But for now I preferred a more explicit version until we get a correct result, at which point we can begin more efficiently expressing the constraints while verifying that it does not affect the solution.

Or is it the case that we shouldn't be creating any slices not in conflict sets to begin with? Looking at the results, most of these non-conflicting slices are as you would expect -- low eccentricity regions with uniform high intensity/low contrast surrounded by high contrast membranes such that they form a single basin in watershed.

**Comment by aschampion** [comment]
catsop/python-sopnet@2d020c3d4800864f0465d926bb01d7705b67f245 fixes the conflict-slices-in-segments and conflicting-slices-in-solution issues. I would have preferred to load `ConflictSets` in `PostgreSqlSliceStore::getSlicesByBlocks` for consistency, but because `SegmentGuarantor` incrementally collects slices as it expands blocks (which is good), it had to be done there. I'll revisit the exclusivity constraints later today, but for now the solution appears to be consistent and non-conflicting.
