### ISSUE TITLE
DVID data sources don't render in WebGL-enabled tile layer

### ISSUE THREAD

**Issue by unidesigner** [catsop/catsop#44]
Being on commit catsop/CATMAID@fc3f29ec, I am not able to see images coming from a DVID tile source type 6 (imageblk voxels) when I enable 'Prefer WebGL Layers' in the settings. If I copy-paste the image request in a new Chrome window, the requested image shows just fine. Testing with the Catsop example data, which fetches from precomputed tile pyramids, the images show fine with the WebGL enabled layers. I see the same for DVID tilesources. Any ideas why this could be? Could this be due to an outdated version of catsop/CATMAID? Thanks

**Comment by aschampion** [comment]
This is almost certainly due to changes in DVID's response encoding, which were fixed in upstream CATMAID in catmaid/CATMAID@a684ef86f6d172c58130831a7dd6eb8e5aca105a.

Will be fixed here once I merge upstream CATMAID and get rid of the old South migrations.

**Comment by unidesigner** [comment]
This solved it, thanks! I cherry picked the commit locally for now.
